# Generated by Django 4.0.3 on 2022-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0009_delete_ownedgames'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(to='game_store.games'),
        ),
    ]
