# Generated by Django 4.0.3 on 2022-03-29 17:35

import Game_store_project.auth_app.validtors
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=15, unique=True, validators=[Game_store_project.auth_app.validtors.validate_only_letters_numbers_underscores])),
                ('profile_image', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
