# Generated by Django 4.0.3 on 2022-04-04 11:17

import Game_store_project.auth_app.validtors
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinValueValidator(2), Game_store_project.auth_app.validtors.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinValueValidator(2), Game_store_project.auth_app.validtors.validate_only_letters]),
            preserve_default=False,
        ),
    ]
