# Generated by Django 4.0.3 on 2022-04-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Pleven', 'Pleven'), ('Other', 'Other')], max_length=20)),
                ('hobbies', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='more_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.moreinfo'),
        ),
    ]
