# Generated by Django 4.0.3 on 2022-04-04 12:01

import Game_store_project.auth_app.validtors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestoreuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='gamestoreuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='gamestoreuser',
            name='username',
            field=models.CharField(default=1, max_length=25, unique=True, validators=[Game_store_project.auth_app.validtors.validate_only_letters_numbers_underscores]),
            preserve_default=False,
        ),
    ]
