# Generated by Django 4.0.3 on 2022-04-06 19:44

import Game_store_project.auth_app.validtors
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), Game_store_project.auth_app.validtors.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), Game_store_project.auth_app.validtors.validate_only_letters]),
        ),
    ]
