# Generated by Django 4.0.3 on 2022-04-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0003_games_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
