# Generated by Django 4.0.3 on 2022-04-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
