# Generated by Django 4.0.3 on 2022-04-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0008_ownedgames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnedGames',
        ),
    ]
