# Generated by Django 4.0.3 on 2022-04-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
